version: "3"
services:

    selenium:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: scraping_selenium
        ports:
            - 4000:4000
        privileged: true
        command: tail -f /dev/null
        volumes:
            - ./:/home/jovyan/work